<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Link;


/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{
    const LIMIT_LINKS = 10;

    public function getAllLinks($page = 1)
    {
        return $this->findBy([], [], self::LIMIT_LINKS, self::LIMIT_LINKS * ($page - 1));
    }

    /**
     * @param Link $link
     * @return bool|string
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function addLink(Link $link)
    {
        try {
            $this->_em->persist($link);
            $this->_em->flush();
            return true;
        } catch (\Error $e) {
            return $e->getMessage();
        }
    }

    /**
     * @param $data
     * @return Link
     */
    public function getNewLink($data)
    {
        $link = new Link();

        if (array_key_exists('full_link', $data)) {
            $link->setFullLink($data['full_link']);
        }

        if (array_key_exists('short_link', $data)) {
            $link->setShortLink($data['short_link']);
        } else {
            $link->setShortLink('generate');
        }

        $link->setCountVisit(0);

        return $link;
    }


    /**
     * @param Link $link
     * @return $this
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function increaseCount(Link $link)
    {
        $link->setCountVisit($link->getCountVisit() + 1);

        try {
            $this->_em->persist($link);
            $this->_em->flush();
        } catch (\Error $e) {

        }

        return $this;
    }
}
